"""initial runs and events

Revision ID: 6d6f3c5d8725
Revises: 
Create Date: 2026-09-23 14:51:00.855098
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '6d6f3c5d8725'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('graph_name', sa.String(length=128), nullable=False),
    sa.Column('thread_id', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('model_profile', sa.String(length=128), nullable=True),
    sa.Column('input', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_runs')),
    schema='app'
    )
    op.create_index(op.f('ix_app_runs_created_at'), 'runs', ['created_at'], unique=False, schema='app')
    op.create_index(op.f('ix_app_runs_graph_name'), 'runs', ['graph_name'], unique=False, schema='app')
    op.create_index(op.f('ix_app_runs_status'), 'runs', ['status'], unique=False, schema='app')
    op.create_index(op.f('ix_app_runs_thread_id'), 'runs', ['thread_id'], unique=False, schema='app')
    op.create_table('events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('node_path', sa.String(length=512), nullable=True),
    sa.Column('span_id', sa.String(length=64), nullable=True),
    sa.Column('parent_span_id', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['app.runs.id'], name=op.f('fk_events_run_id_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events')),
    schema='app'
    )
    op.create_index('ix_events_run_id_seq', 'events', ['run_id', 'seq'], unique=True, schema='app')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_events_run_id_seq', table_name='events', schema='app')
    op.drop_table('events', schema='app')
    op.drop_index(op.f('ix_app_runs_thread_id'), table_name='runs', schema='app')
    op.drop_index(op.f('ix_app_runs_status'), table_name='runs', schema='app')
    op.drop_index(op.f('ix_app_runs_graph_name'), table_name='runs', schema='app')
    op.drop_index(op.f('ix_app_runs_created_at'), table_name='runs', schema='app')
    op.drop_table('runs', schema='app')
    # ### end Alembic commands ###
